- hosts: windows_server
  gather_facts: no
  tasks:

    - name: Update WinRM Trusted Host list
      ansible.windows.win_shell: Set-Item WSMan:localhost\client\trustedhosts -value "{{ winrmtrustedhosts }}" -Force

    - name: Remove directory structure
      ansible.windows.win_file:
        path: C:\Temp
        state: absent

    - name: Enable RDP
      win_regedit:
        key: HKLM:\SYSTEM\CurrentControlSet\Control\Terminal Server
        name: fDenyTSConnections
        data: 0
        type: dword

    - name: Firewall rule to allow Remote Desktop on 3389/TCP
      community.windows.win_firewall_rule:
        name: Remote Desktop - User Mode (TCP-In)
        localport: 3389
        action: allow
        direction: in
        protocol: tcp
        profiles: domain,private,public
        state: present
        enabled: yes

    - name: Firewall rule to allow Remote Desktop on 3389/UDP
      community.windows.win_firewall_rule:
        name: Remote Desktop - User Mode (UDP-In)
        localport: 3389
        action: allow
        direction: in
        protocol: UDP
        profiles: domain,private,public
        state: present
        enabled: yes

    - name: Firewall rule to allow WINRM over HTTPS on TCP port 5986
      community.windows.win_firewall_rule:
        name: Windows Remote Management (HTTPS-In)
        localport: 5986
        action: allow
        direction: in
        protocol: tcp
        profiles: domain,private,public
        state: present
        enabled: yes

    - name: Disable Firewall rule Windows Remote Management (HTTP-In)
      community.windows.win_firewall_rule:
        name: Windows Remote Management (HTTP-In)
        state: present
        enabled: no

    - name: Remove WinRM HTTP listner
      ansible.windows.win_powershell:
        script: |
                & winrm delete winrm/config/Listener?Address=*+Transport=HTTP

    - name: Final Reboot before Post
      ansible.windows.win_reboot: